#!/bin/bash
# 18 - The two notices that never go away
#
# Run INSIDE the VM:   bash 18-avisos-que-no-se-apagan.sh
# (the filename is kept as it is on purpose: its URL is already published)
#
# SYMPTOM A - "Update System" comes back on every boot even when everything is
#   up to date. omarchy-provision-first-run only marks first-run as done when
#   NO step fails. Here enable-user-units.sh failed every time, for TWO
#   reasons:
#     1. The six .service files were never installed in
#        /usr/lib/systemd/user/. Upstream ships them in the omarchy-settings
#        package, which does not exist for
#        ARM (docs/file-layout.md: "systemd/user/*.service → /usr/lib/systemd/user/").
#     2. Those .service files invoke /usr/bin/omarchy-*, and this image had the
#        comandos en /usr/local/bin.
#   Never being marked, first-run repeats on every login and wifi.sh re-raises
#   the notice.
#
# SYMPTOM B - "Linux kernel has been updated. Reboot?" always appears.
#   omarchy-update-restart looks for a vmlinuz inside /usr/lib/modules/<ver>/
#   that belongs to a package. On Arch x86_64 the linux package installs one;
#   on Arch Linux ARM, linux-aarch64 leaves the image in /boot/Image and never
#   creates that vmlinuz. The loop finds nothing, kernel_updated stays true and
#   it asks for a reboot on every update. Rebooting does not help: the
#   condition cannot
#   volverse falsa.
set -uo pipefail
echo "==> A. omarchy commands into /usr/bin (where the tree expects them)"
n=0
for f in /usr/share/omarchy/bin/*; do
  [ -f "$f" ] || continue
  sudo ln -sfn "$f" "/usr/bin/$(basename "$f")" && n=$((n+1))
done
echo "   $n comandos enlazados en /usr/bin"

echo "==> A2. unidades de usuario donde systemd las busca"
# This was the missing step: without the .service files installed,
# enable-user-units.sh cannot work however many paths are fixed.
if [ -d /usr/share/omarchy/default/systemd/user ]; then
  sudo install -d /usr/lib/systemd/user
  sudo cp -a /usr/share/omarchy/default/systemd/user/. /usr/lib/systemd/user/
  echo "   $(ls /usr/lib/systemd/user/*.service 2>/dev/null | wc -l) unidades disponibles"
else
  echo "   no encuentro /usr/share/omarchy/default/systemd/user"
fi

echo "==> B. envoltorio para el aviso de kernel"
sudo install -Dm755 /dev/stdin /usr/local/bin/omarchy-update-restart <<'KRN'
#!/bin/bash
if [ -z "${OMARCHY_SKIP_KERNEL_CHECK:-}" ]; then
  # modules.dep is generated by depmod and belongs to no package.
  # modules.builtin does ship with linux-aarch64, so it tells us whether the
  # running kernel's modules directory is the installed package's.
  pkg=$(pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.builtin 2>/dev/null \
        || pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.order 2>/dev/null || true)
  [ -n "$pkg" ] && export OMARCHY_KERNEL_CURRENT=1
fi
REAL=/usr/bin/omarchy-update-restart
[ -x "$REAL" ] || exit 0
if [ -n "${OMARCHY_KERNEL_CURRENT:-}" ]; then
  sed 's#^kernel_updated=true$#kernel_updated=false#' "$REAL" | bash -s -- "$@"
else
  exec "$REAL" "$@"
fi
KRN
echo "   /usr/local/bin/omarchy-update-restart"

echo "==> C. completar first-run para que deje de repetirse"
bash /usr/share/omarchy/install/user/first-run/enable-user-units.sh \
  && echo "   enable-user-units.sh: works now" \
  || echo "   sigue fallando: mira 'systemctl --user status' de las seis unidades"
omarchy-provision-first-run --force 2>&1 | tail -3

echo "==> verification"
printf "   unidades instaladas: %s\n" "$(ls /usr/lib/systemd/user/*.service 2>/dev/null | wc -l)"
printf "   first-run marcado:  %s\n" "$(omarchy-done check first-run-user && echo sí || echo NO)"
printf "   kernel en ejecución: %s\n" "$(uname -r)"
printf "   lo posee:            %s\n" "$(pacman -Qoq /usr/lib/modules/"$(uname -r)"/modules.builtin 2>/dev/null || echo "(nadie)")"
echo "   omarchy-update-restart should not ask for a reboot from now on."
